#Example configuration file, remember to remove "example_" from the file after you modified it!

#Discord Bot token:
#To get your bot's token, go to https://discord.com/developers/applications click "New application",
#click "Bot" on the left bar, click "Add bot" and confirm, then click "Copy" under "Click to reveal token"
token: ""

#Driver type, aka what database to use. For now we support only "mysql"
drivername: "mysql"
#DB Info, like username, password...

#MySQL
datasourcename: "user:pass@tcp(ip:3306)/database"

#Log level. Possible value are error, warning, informational and debug
loglevel: informational